version: "3.8"  # or "4" if you're targeting Docker Compose v2+ CLI

services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
